FROM dockerops/dockerops-base
MAINTAINER Stefano Alberto Russo <stefano.russo@gmail.com>

#----------------------
# Demo Stuff
#----------------------

#RUN apt-get install -y somepackage

RUN echo "touch /started.log" >> /entrypoint-local.sh

















