FROM dockerops/base
MAINTAINER Stefano Alberto Russo <stefano.russo@gmail.com>

#----------------------
# Demo Stuff
#----------------------


#----------------------
# Startup
#----------------------

ENTRYPOINT ["/docker-entrypoint.sh"]




















