FROM dockerops/dockerops-base-ubuntu14.04
MAINTAINER Stefano Alberto Russo <stefano.russo@gmail.com>

#----------------------
# Demo Stuff
#----------------------

#RUN apt-get update
#RUN apt-get install -y somepackage

# Prestartup
COPY prestartup_dockerops-demo.sh /prestartup/

















